### ISSUE TITLE
What do we need to do to open source this thing?

### ISSUE THREAD

**Issue by TessHuelskamp** [tjkkelly/bot-repo#34]
Since we went through the whole trek of getting our private keys out of here, I'd like to make this repo public.

Think we'd get #24 into an acceptable state. It would also be nice to have a blog post about this thing since I hear the cool kids do that.

Not sure what else we need to do

**Comment by tjkkelly** [comment]
done

**Comment by TessHuelskamp** [comment]
![](http://giphygifs.s3.amazonaws.com/media/7xLwnrezR8rbW/giphy.gif)
